msgbox "Game Done"
msgbox "Kill Me Now While You Can You GAY Sh*t!"
msgbox "Launching... 15..."
msgbox "Launching... 14..."
msgbox "Launching... 13..."
msgbox "Launching... 12..."
msgbox "Launching... 11..."
msgbox "Launching... 10..."
msgbox "Launching... 9..."
msgbox "Launching... 8..."
msgbox "Launching... 7..."
msgbox "Launching... 6..."
msgbox "Launching... 5..."
msgbox "Launching... 4..."
msgbox "Launching... 3..."
msgbox "Launching... 2..."
msgbox "Launching... 1..."
msgbox "Launching... 0..."
msgbox "Bye Bye!"
msgbox "Go!"
